/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.labAssistant;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import source.hospital.Hospital;
import source.patient.Patient;
import source.patient.Procedure;
import source.userAccount.UserAccount;
import source.util.UtilFunctions;

/**
 *
 * @author GaurangDeshpande
 */
public class AddProcedureJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private UserAccount account;
    private Hospital hospital;
    private Patient patient;
    private static Logger log;
    
    /**
     * Creates new form AddProcedureJPanel
     */
    AddProcedureJPanel(JPanel cardContainer, UserAccount account, Hospital hospital, Patient patient) {
        initComponents();
        this.cardContainer = cardContainer;
        this.account = account;
        this.hospital = hospital;
        this.patient = patient;
        log = Logger.getLogger(AddProcedureJPanel.class);
        lblLoggedInUser.setText(account.getEmployee().getPerson().getLastName()+", "+account.getEmployee().getPerson().getFirstName());
        
        initialSetup();
        populateDetailsOnScreen();
    }

    private void populateDetailsOnScreen(){
        Date date = new Date();
        lblVisitDate.setText(String.valueOf(date));
        lblPerformedBy.setText(account.getEmployee().getPerson().getFirstName()+" "+account.getEmployee().getPerson().getLastName());
        //lblRequestedBy.setText("");
        lblPatient.setText(patient.getPerson().getFirstName()+" "+patient.getPerson().getLastName());
        //lblRequestDate.setText("");
        lblCompletionDate.setText(String.valueOf(date));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedInUser = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblVisitDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblErrVisitReason = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProcedureType = new javax.swing.JTextField();
        lblErrProcedureType = new javax.swing.JLabel();
        btnAddProcedure = new javax.swing.JButton();
        txtVisitReason = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblErrDescription = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPerformedBy = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRequestedBy = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRequestDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCompletionDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblHeading.setText("Add Procedure");

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Visit Time:");

        lblVisitDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblVisitDate.setText("Reason for visit:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Reason for visit:");

        lblErrVisitReason.setForeground(new java.awt.Color(255, 51, 0));
        lblErrVisitReason.setText("lblErr");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Procedure Type:");

        txtProcedureType.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lblErrProcedureType.setForeground(new java.awt.Color(255, 51, 0));
        lblErrProcedureType.setText("lblErr");

        btnAddProcedure.setBackground(new java.awt.Color(51, 51, 51));
        btnAddProcedure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddProcedure.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProcedure.setText("Add Procedure");
        btnAddProcedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProcedureActionPerformed(evt);
            }
        });

        txtVisitReason.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Description:");

        txtDescription.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lblErrDescription.setForeground(new java.awt.Color(255, 51, 0));
        lblErrDescription.setText("lblErr");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Performed By:");

        lblPerformedBy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPerformedBy.setText("Reason for visit:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Requested By:");

        lblRequestedBy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblRequestedBy.setText("Requested By");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Request Date:");

        lblRequestDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblRequestDate.setText("Request Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Patient:");

        lblPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPatient.setText("Requested By");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Completion Date:");

        lblCompletionDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCompletionDate.setText("Completion Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRequestedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(lblPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblPerformedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVisitReason, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrProcedureType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrVisitReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProcedureType, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(lblRequestDate, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(btnAddProcedure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblCompletionDate, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerformedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVisitReason, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrVisitReason))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProcedureType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrProcedureType))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrDescription))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequestedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequestDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompletionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddProcedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProcedureActionPerformed
        // TODO add your handling code here:
        boolean allDataEnteredCorrectly = validateData();
        if(allDataEnteredCorrectly){
            log.info(UtilFunctions.encrypt("ADD_PROC : "+account.getEmployee()));
            Procedure procedure = patient.getProcedureDirectory().carryOutNewProcedure();
            procedure.setProcedureType(txtProcedureType.getText().trim());
            procedure.setProcedureDescription(txtDescription.getText().trim());
            if(!lblRequestedBy.getText().equals("")){
                //procedure.setRequestedBy(lblRequestedBy.getText());
            }
            procedure.setCompletedBy(account.getEmployee());
            procedure.setPerformedOn(patient);
            procedure.setStatus("Complete");
            if(!lblRequestDate.getText().equals("")){
                //procedure.setRequestDate(requestDate);
            }
            Date lastVisit = new Date();
            procedure.setCompletionDate(lastVisit);
            
            patient.setLastVisited(lastVisit);
            patient.setComments(txtVisitReason.getText().trim());
            
            procedure.setPurpose(txtVisitReason.getText().trim());
            procedure.setVisitDate(lastVisit);

            initialSetup();
            if(patient.getPerson().getEmailAddress()!=null){
                UtilFunctions.sendEmail(patient.getPerson().getEmailAddress(), patient.getPerson().getFirstName()+" "+patient.getPerson().getLastName(), "Visit for procedure", txtVisitReason.getText().trim());
            }
            JOptionPane.showMessageDialog(null,"Procedure Added!", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProcedureActionPerformed

    private void initialSetup(){
        txtVisitReason.setText("");
        txtProcedureType.setText("");
        txtDescription.setText("");
        
        lblErrDescription.setVisible(false);
        lblErrProcedureType.setVisible(false);
        lblErrVisitReason.setVisible(false);
    }
    
    private boolean validateData(){
        int i=0;
        //Validate Procedure Type
        if (txtProcedureType.getText().trim().equalsIgnoreCase("") || txtProcedureType.getText().trim() == null) {
            txtProcedureType.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrProcedureType.setVisible(true);
            lblErrProcedureType.setText("Please enter Procedure Type");
            i++;
        } else if (!UtilFunctions.validateNumberAndText(txtProcedureType.getText().trim())) {
            txtProcedureType.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrProcedureType.setVisible(true);
            lblErrProcedureType.setText("Please enter only text and numbers in Procedure Type");
            i++;
        } else {
            lblErrProcedureType.setVisible(false);
            txtProcedureType.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        }
        
        //Validate Description
        if(txtDescription.getText().trim().equalsIgnoreCase("")||txtDescription.getText().trim()==null){
            txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrDescription.setVisible(false);
        }
        else if(!UtilFunctions.validateNumberAndText(txtDescription.getText().trim())){
            txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrDescription.setVisible(true);
            lblErrDescription.setText("Please enter only text and numbers in Description");
            i++;
        }
        else{
            txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrDescription.setVisible(false);
        }
        
        if(txtVisitReason.getText().trim().equalsIgnoreCase("")||txtVisitReason.getText().trim()==null){
            txtVisitReason.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrVisitReason.setVisible(true);
            lblErrVisitReason.setText("Please enter visit reason");
            i++;
        }
        else if(!UtilFunctions.validateNumberAndText(txtVisitReason.getText().trim())){
            txtVisitReason.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrVisitReason.setVisible(true);
            lblErrVisitReason.setText("Please enter only text and numbers");
            i++;
        }
        else{
            txtVisitReason.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrVisitReason.setVisible(false);
        }
        
        if(i==0){
            return true;
        }
        else{
            return false;
        }
    }
    
    private void goBack(){
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProcedure;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCompletionDate;
    private javax.swing.JLabel lblErrDescription;
    private javax.swing.JLabel lblErrProcedureType;
    private javax.swing.JLabel lblErrVisitReason;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPerformedBy;
    private javax.swing.JLabel lblRequestDate;
    private javax.swing.JLabel lblRequestedBy;
    private javax.swing.JLabel lblVisitDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtProcedureType;
    private javax.swing.JTextField txtVisitReason;
    // End of variables declaration//GEN-END:variables
}
