/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.securityTeam;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import source.department.SecurityDepartment;
import source.userAccount.UserAccount;
import source.workQueue.SpecialMedicalWorkRequest;
import source.workQueue.WorkRequest;

/**
 *
 * @author GaurangDeshpande
 */
public class ManageSpecialRequestJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private UserAccount account;
    private SecurityDepartment securityDepartment;
    /**
     * Creates new form ManageSpecialRequestJPanel
     */
    ManageSpecialRequestJPanel(JPanel cardContainer, UserAccount account, SecurityDepartment securityDepartment) {
        initComponents();
        this.cardContainer = cardContainer;
        this.account = account;
        this.securityDepartment = securityDepartment;
        
        lblLoggedInUser.setText(account.getEmployee().getPerson().getLastName()+", "+account.getEmployee().getPerson().getFirstName());
        
        populateRequestsTable();
    }
    
    void populateRequestsTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblSpecialRequests.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request : securityDepartment.getWorkQueue().getWorkRequestList()) {
            if (request instanceof SpecialMedicalWorkRequest) {
                Object[] row = new Object[6];
                row[0] = request;
                row[1] = request.getRequestCreator();
                row[2] = request.getRequestAssignee() == null ? null : request.getRequestAssignee();
                row[3] = request.getRequestCreationDate();
                row[4] = request.getStatus();
                row[5] = request.getRequestOutcome();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedInUser = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpecialRequests = new javax.swing.JTable();
        btnAssignRequest = new javax.swing.JButton();
        btnProcessRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblHeading.setText("Manage Requests");

        tblSpecialRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Message", "Sender", "Assignee", "Raised On", "Status", "Comments"
            }
        ));
        jScrollPane1.setViewportView(tblSpecialRequests);

        btnAssignRequest.setBackground(new java.awt.Color(51, 51, 51));
        btnAssignRequest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssignRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRequest.setText("Assign To Me");
        btnAssignRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRequestActionPerformed(evt);
            }
        });

        btnProcessRequest.setBackground(new java.awt.Color(51, 51, 51));
        btnProcessRequest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProcessRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 951, Short.MAX_VALUE)
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAssignRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnProcessRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcessRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRequestActionPerformed
        // TODO add your handling code here:
        int selectedRequestRow = tblSpecialRequests.getSelectedRow();
        if(selectedRequestRow<0){
            JOptionPane.showMessageDialog(null, "Please seect a request to assign", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        WorkRequest request = (WorkRequest) tblSpecialRequests.getValueAt(selectedRequestRow, 0);
        if(request.getStatus().equals("Initiated")){
            request.setRequestAssignee(account.getEmployee());
            request.setStatus("Pending");
            populateRequestsTable();
        }
        else if(request.getRequestAssignee().equals(account.getEmployee())){
            JOptionPane.showMessageDialog(null, "Request already assigned to you", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            JOptionPane.showMessageDialog(null, "Request already being processed by someone else", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnAssignRequestActionPerformed

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:
        int selectedRequestRow = tblSpecialRequests.getSelectedRow();
        if(selectedRequestRow<0){
            JOptionPane.showMessageDialog(null, "Please select a request to process", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        SpecialMedicalWorkRequest request = (SpecialMedicalWorkRequest) tblSpecialRequests.getValueAt(selectedRequestRow, 0);
        if(null==request.getRequestAssignee()){
            JOptionPane.showMessageDialog(null, "Please assign the request first, to process", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(request.getRequestAssignee().equals(account.getEmployee())){
            if(request.getStatus().equalsIgnoreCase("Initiated")){
                JOptionPane.showMessageDialog(null, "Please assign the request before processing", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(!request.getStatus().equalsIgnoreCase("Complete")){
                request.setStatus("Processing");
            }
            ProcessSpecialRequestJPanel processSpecialRequestJPanel = new ProcessSpecialRequestJPanel(cardContainer, account, request);
            cardContainer.add("processSpecialRequestJPanel", processSpecialRequestJPanel);
            CardLayout layout = (CardLayout) cardContainer.getLayout();
            layout.next(cardContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Request is not assigned to you", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void goBack(){
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JTable tblSpecialRequests;
    // End of variables declaration//GEN-END:variables
}
