/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.doctor;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import source.hospital.Hospital;
import source.patient.Patient;
import source.patient.Prescription;
import source.userAccount.UserAccount;
import source.util.Util;
import source.util.UtilFunctions;

/**
 *
 * @author GaurangDeshpande
 */
public class AddPrescriptionJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private UserAccount account;
    private Patient patient;
    private Hospital hospital;
    private static Logger log;
    /**
     * Creates new form AddPrescriptionJPanel
     */
    AddPrescriptionJPanel(JPanel cardContainer, UserAccount account, Patient patient, Hospital hospital) {
        initComponents();
        this.cardContainer = cardContainer;
        this.account = account;
        this.patient = patient;
        this.hospital = hospital;
        log = Logger.getLogger(AddPrescriptionJPanel.class);
        
        lblLoggedInUser.setText(account.getEmployee().getPerson().getLastName()+", "+account.getEmployee().getPerson().getFirstName());
        
        lblVisitDate.setText(String.valueOf(new Date()));
        initialSetup();
    }
    
    private void initialSetup() {
        txtMedicineName.setText("");
        lblErrMedicineName.setText("");
        lblErrMedicineName.setVisible(false);
        
        txtPrescribedOn.setText("MM/dd/yyyy");
        txtPrescribedOn.setForeground(new Color(153,153,153));
        lblErrPrescribedOn.setText("");
        lblErrPrescribedOn.setVisible(false);
        
        txtPrescribedTill.setText("MM/dd/yyyy");
        txtPrescribedTill.setForeground(new Color(153,153,153));
        lblErrPrescribedTill.setText("");
        lblErrPrescribedTill.setVisible(false);
        
        txtDailyDosages.setText("");
        lblErrDailyDosages.setText("");
        lblErrDailyDosages.setVisible(false);
        
        txtPrescriptionDescription.setText("");
        lblErrDescription.setText("");
        lblErrDescription.setVisible(false);
        
        txtVisitReason.setText("");
        lblErrVisitReason.setText("");
        lblErrVisitReason.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedInUser = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblErrVisitReason = new javax.swing.JLabel();
        lblVisitDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVisitReason = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        lblErrMedicineName = new javax.swing.JLabel();
        txtPrescribedOn = new javax.swing.JTextField();
        txtDailyDosages = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrescriptionDescription = new javax.swing.JTextArea();
        lblErrPrescribedOn = new javax.swing.JLabel();
        lblErrDailyDosages = new javax.swing.JLabel();
        lblErrDescription = new javax.swing.JLabel();
        btnAddPrescription = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtPrescribedTill = new javax.swing.JTextField();
        lblErrPrescribedTill = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblHeading.setText("Add Prescription");

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Visit Time:");

        lblErrVisitReason.setForeground(new java.awt.Color(255, 51, 0));
        lblErrVisitReason.setText("lblErr");

        lblVisitDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblVisitDate.setText("Reason for visit:");

        txtVisitReason.setColumns(20);
        txtVisitReason.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtVisitReason.setRows(4);
        jScrollPane1.setViewportView(txtVisitReason);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Reason for visit:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Medicine Name:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Prescribed on:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Daily Dose:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Description:");

        txtMedicineName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lblErrMedicineName.setForeground(new java.awt.Color(255, 51, 0));
        lblErrMedicineName.setText("lblErr");

        txtPrescribedOn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPrescribedOn.setForeground(new java.awt.Color(153, 153, 153));
        txtPrescribedOn.setText("MM/dd/yyyy");
        txtPrescribedOn.setToolTipText("");
        txtPrescribedOn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrescribedOnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrescribedOnFocusLost(evt);
            }
        });

        txtDailyDosages.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txtPrescriptionDescription.setColumns(20);
        txtPrescriptionDescription.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPrescriptionDescription.setRows(4);
        jScrollPane2.setViewportView(txtPrescriptionDescription);

        lblErrPrescribedOn.setForeground(new java.awt.Color(255, 51, 0));
        lblErrPrescribedOn.setText("lblErr");

        lblErrDailyDosages.setForeground(new java.awt.Color(255, 51, 0));
        lblErrDailyDosages.setText("lblErr");

        lblErrDescription.setForeground(new java.awt.Color(255, 51, 0));
        lblErrDescription.setText("lblErr");

        btnAddPrescription.setBackground(new java.awt.Color(51, 51, 51));
        btnAddPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddPrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPrescription.setText("Add Prescription");
        btnAddPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrescriptionActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Prescribed Till:");

        txtPrescribedTill.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPrescribedTill.setForeground(new java.awt.Color(153, 153, 153));
        txtPrescribedTill.setText("MM/dd/yyyy");
        txtPrescribedTill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrescribedTillFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrescribedTillFocusLost(evt);
            }
        });

        lblErrPrescribedTill.setForeground(new java.awt.Color(255, 51, 0));
        lblErrPrescribedTill.setText("lblErr");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrescribedTill, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrPrescribedTill, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrescribedOn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrPrescribedOn, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDailyDosages, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrDailyDosages, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblVisitDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrVisitReason, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrVisitReason)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrMedicineName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrescribedOn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrPrescribedOn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrescribedTill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrPrescribedTill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDailyDosages, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrDailyDosages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrescriptionActionPerformed
        // TODO add your handling code here:
        boolean allDataEnteredCorrectly = validateData();
        if(allDataEnteredCorrectly){
            log.info(UtilFunctions.encrypt("PRES : "+account.getEmployee()));
            Prescription prescription = patient.getPrescriptionHistory().prescribeMedicine();

            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            prescription.setMedicineName(txtMedicineName.getText().trim());
            try{
                prescription.setPrescribedOn(formatter.parse(txtPrescribedOn.getText().trim()));
                prescription.setPrescribedTill(formatter.parse(txtPrescribedTill.getText().trim()));
            }
            catch(Exception e){
                String message = e.getMessage();
            }
            prescription.setDailyDosage(Integer.parseInt(txtDailyDosages.getText().trim()));
            prescription.setPrescriptionDescription(txtPrescriptionDescription.getText().trim());
            
            Date lastVisit = new Date();
            patient.setLastVisited(lastVisit);
            patient.setComments(txtVisitReason.getText().trim());
            
            prescription.setPurpose(txtVisitReason.getText().trim());
            prescription.setVisitDate(lastVisit);

            initialSetup();
            if(patient.getPerson().getEmailAddress()!=null){
                UtilFunctions.sendEmail(patient.getPerson().getEmailAddress(), patient.getPerson().getFirstName()+" "+patient.getPerson().getLastName(), "Visit for Prescription", txtVisitReason.getText().trim());
            }
            
            JOptionPane.showMessageDialog(null,"Prescription Added!", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddPrescriptionActionPerformed

    private void txtPrescribedOnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrescribedOnFocusGained
        // TODO add your handling code here:
        if(txtPrescribedOn.getText().equals("MM/dd/yyyy")){
            txtPrescribedOn.setText(Util.BLANK_QUOTES);
        }
        txtPrescribedOn.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPrescribedOnFocusGained

    private void txtPrescribedOnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrescribedOnFocusLost
        // TODO add your handling code here:
        if(txtPrescribedOn.getText().isEmpty()||txtPrescribedOn.getText().equals(Util.BLANK_QUOTES)||txtPrescribedOn.getText().equalsIgnoreCase("MM/dd/yyyy")){
            txtPrescribedOn.setText("MM/dd/yyyy");
            txtPrescribedOn.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPrescribedOnFocusLost

    private void txtPrescribedTillFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrescribedTillFocusGained
        // TODO add your handling code here:
        if(txtPrescribedTill.getText().equals("MM/dd/yyyy")){
            txtPrescribedTill.setText(Util.BLANK_QUOTES);
        }
        txtPrescribedTill.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPrescribedTillFocusGained

    private void txtPrescribedTillFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrescribedTillFocusLost
        // TODO add your handling code here:
        if(txtPrescribedTill.getText().isEmpty()||txtPrescribedTill.getText().equals(Util.BLANK_QUOTES)||txtPrescribedTill.getText().equalsIgnoreCase("MM/dd/yyyy")){
            txtPrescribedTill.setText("MM/dd/yyyy");
            txtPrescribedTill.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPrescribedTillFocusLost

    private boolean validateData(){
        int i=0;
        //Validate Medicine Name
        if (txtMedicineName.getText().trim().equalsIgnoreCase("") || txtMedicineName.getText().trim() == null) {
            txtMedicineName.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrMedicineName.setVisible(true);
            lblErrMedicineName.setText("Please enter Medicine Name");
            i++;
        } else if (!UtilFunctions.validateNumberAndText(txtMedicineName.getText().trim())) {
            txtMedicineName.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrMedicineName.setVisible(true);
            lblErrMedicineName.setText("Please enter only numbers and text in Medicine Name");
            i++;
        } else {
            lblErrMedicineName.setVisible(false);
            txtMedicineName.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        }
        
        //Validate Prescribed On
        if(txtPrescribedOn.getText().trim().equalsIgnoreCase("")||txtPrescribedOn.getText().trim()==null||txtPrescribedOn.getText().equalsIgnoreCase("MM/dd/yyyy")){
            txtPrescribedOn.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrPrescribedOn.setVisible(true);
            lblErrPrescribedOn.setText("Please enter Prescribed On date");
            i++;
        }
        else if(!UtilFunctions.validateDateFormat(txtPrescribedOn.getText().trim())){
            txtPrescribedOn.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrPrescribedOn.setVisible(true);
            lblErrPrescribedOn.setText("Please enter date in mm/dd/yyyy format");
            i++;
        }
        else if(!UtilFunctions.validatePastDate(txtPrescribedOn.getText().trim())){
            txtPrescribedOn.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrPrescribedOn.setVisible(true);
            lblErrPrescribedOn.setText("Past dates not allowed!");
            i++;
        }
        else{
            txtPrescribedOn.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrPrescribedOn.setVisible(false);
        }
        
        //Validate Prescribed Till
        if(txtPrescribedTill.getText().trim().equalsIgnoreCase("")||txtPrescribedTill.getText().trim()==null||txtPrescribedTill.getText().equalsIgnoreCase("MM/dd/yyyy")){
            txtPrescribedTill.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrPrescribedTill.setVisible(true);
            lblErrPrescribedTill.setText("Please enter Prescribed Till date");
            i++;
        }
        else if(!UtilFunctions.validateDateFormat(txtPrescribedTill.getText().trim())){
            txtPrescribedTill.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrPrescribedTill.setVisible(true);
            lblErrPrescribedTill.setText("Please enter date in mm/dd/yyyy format");
            i++;
        }
        else if(!UtilFunctions.validateDateSequence(txtPrescribedTill.getText().trim(),txtPrescribedOn.getText().trim())){
            txtPrescribedTill.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrPrescribedTill.setVisible(true);
            lblErrPrescribedTill.setText("Please enter Precribed Till date after Prescribed On date");
            i++;
        }
        else{
            txtPrescribedTill.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrPrescribedTill.setVisible(false);
        }
        
        //Validate Daily Doses
        if(txtDailyDosages.getText().trim().equalsIgnoreCase("")||txtDailyDosages.getText().trim()==null){
            txtDailyDosages.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrDailyDosages.setVisible(true);
            lblErrDailyDosages.setText("Please enter Daily Dose");
            i++;
        }
        if(!UtilFunctions.validateNumericalsOnly(txtDailyDosages.getText().trim())){
            txtDailyDosages.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrDailyDosages.setVisible(true);
            lblErrDailyDosages.setText("Please enter numbers in Daily Dose");
            i++;
        }
        else{
            txtDailyDosages.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrDailyDosages.setVisible(false);
        }
        
        //Validate Dosage Description
        if(txtPrescriptionDescription.getText().trim().equalsIgnoreCase("")||txtPrescriptionDescription.getText().trim()==null){
            txtPrescriptionDescription.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrDescription.setVisible(false);
        }
        else if(!UtilFunctions.validateNumberAndText(txtPrescriptionDescription.getText().trim())){
            txtPrescriptionDescription.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrDescription.setVisible(true);
            lblErrDescription.setText("Please enter numbers in Blood Glucose Level");
            i++;
        }
        else{
            txtPrescriptionDescription.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrDescription.setVisible(false);
        }
        
        if(txtVisitReason.getText().trim().equalsIgnoreCase("")||txtVisitReason.getText().trim()==null){
            txtVisitReason.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrVisitReason.setVisible(true);
            lblErrVisitReason.setText("Please enter visit reason");
            i++;
        }
        else if(!UtilFunctions.validateNumberAndText(txtVisitReason.getText().trim())){
            txtVisitReason.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            lblErrVisitReason.setVisible(true);
            lblErrVisitReason.setText("Please enter only text and numbers");
            i++;
        }
        else{
            txtVisitReason.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
            lblErrVisitReason.setVisible(false);
        }
        
        if(i==0){
            return true;
        }
        else{
            return false;
        }
    }
    
    private void goBack(){
        cardContainer.remove(this);
        Component[] componentArray = cardContainer.getComponents();
        Component component= componentArray[componentArray.length - 1];
        PatientDetailsJPanel patientDetailsJPanel = (PatientDetailsJPanel) component;
        patientDetailsJPanel.populateTable();
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrescription;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrDailyDosages;
    private javax.swing.JLabel lblErrDescription;
    private javax.swing.JLabel lblErrMedicineName;
    private javax.swing.JLabel lblErrPrescribedOn;
    private javax.swing.JLabel lblErrPrescribedTill;
    private javax.swing.JLabel lblErrVisitReason;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblVisitDate;
    private javax.swing.JTextField txtDailyDosages;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtPrescribedOn;
    private javax.swing.JTextField txtPrescribedTill;
    private javax.swing.JTextArea txtPrescriptionDescription;
    private javax.swing.JTextArea txtVisitReason;
    // End of variables declaration//GEN-END:variables
}
