/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.doctor;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import source.hospital.Hospital;
import source.patient.Patient;
import source.patient.Prescription;
import source.patient.Procedure;
import source.patient.Surgery;
import source.patient.Visit;
import source.patient.VitalSigns;
import source.userAccount.UserAccount;

/**
 *
 * @author GaurangDeshpande
 */
public class PatientDetailsJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private UserAccount account;
    private Hospital hospital;
    private Patient patient;
    private String type;
    /**
     * Creates new form PatientDetailsJPanel
     */
    PatientDetailsJPanel(JPanel cardContainer, UserAccount account, Hospital hospital, Patient patient, String type) {
        initComponents();
        this.cardContainer = cardContainer;
        this.account = account;
        this.hospital = hospital;
        this.patient = patient;
        this.type = type;
        
        lblLoggedInUser.setText(account.getEmployee().getPerson().getLastName()+", "+account.getEmployee().getPerson().getFirstName());
        
        populatePatientHistory();
        if(type.equals("Emergency")){
            btnAddVitalSign.setVisible(false);
            btnAddPrescription.setVisible(false);
            btnAddSurgery.setVisible(false);
            btnAskForLabProcedures.setVisible(false);
            btnMonitorPatient.setVisible(false);
            btnEmergencyAddition.setVisible(true);
        }else if(type.equals("General")){
            btnAddVitalSign.setVisible(true);
            btnAddPrescription.setVisible(true);
            btnAddSurgery.setVisible(true);
            btnAskForLabProcedures.setVisible(true);
            btnMonitorPatient.setVisible(true);
            btnEmergencyAddition.setVisible(false);
        }
    }

    private void populatePatientHistory(){
        lblPatientID.setText(patient.getPatientID());
        lblPatientName.setText(patient.getPerson().getFirstName());
        lblAge.setText(String.valueOf(patient.getPerson().getAge()));
        lblGender.setText(patient.getPerson().getGender());
        
        populateTable();
    }
    
    public void populateTable(){
        ArrayList<Visit> visitHistory = new ArrayList<Visit>();
        Visit visit = null;
        for(VitalSigns vitalSigns:patient.getVitalSignHistory().getVitalSignHistory()){
            visit = new Visit();
            visit.setPurpose(vitalSigns.getPurpose());
            visit.setVisitDate(vitalSigns.getVisitDate());
            visitHistory.add(visit);
        }
        for(Prescription prescription: patient.getPrescriptionHistory().getPrescriptionHistory()){
            visit = new Visit();
            visit.setPurpose(prescription.getPurpose());
            visit.setVisitDate(prescription.getVisitDate());
            visitHistory.add(visit);
        }
        for(Procedure procedure: patient.getProcedureDirectory().getProcedureList()){
            visit = new Visit();
            visit.setPurpose(procedure.getPurpose());
            visit.setVisitDate(procedure.getVisitDate());
            visitHistory.add(visit);
        }
        for(Surgery surgery: patient.getSurgicalHistory().getSurgeryDirectory()){
            visit = new Visit();
            visit.setPurpose(surgery.getPurpose());
            visit.setVisitDate(surgery.getVisitDate());
            visitHistory.add(visit);
        }
        
        Collections.sort(visitHistory, (Visit visit1, Visit visit2) -> visit1.getVisitDate().compareTo(visit2.getVisitDate()));
        Collections.reverse(visitHistory);
        
        DefaultTableModel dtm = (DefaultTableModel)tblPatientHistory.getModel();
        dtm.setRowCount(0);
        for(Visit v:visitHistory){
            Object row[] = new Object[2];
            row[0] = v.getVisitDate();
            row[1] = v.getPurpose();
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedInUser = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        btnAddVitalSign = new javax.swing.JButton();
        btnViewVitalSigns = new javax.swing.JButton();
        btnAddPrescription = new javax.swing.JButton();
        btnViewPrescriptions = new javax.swing.JButton();
        btnAddSurgery = new javax.swing.JButton();
        btnViewSurgeries = new javax.swing.JButton();
        btnMonitorPatient = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientHistory = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnAskForLabProcedures = new javax.swing.JButton();
        btnEmergencyAddition = new javax.swing.JButton();
        btnViewProcedures = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblHeading.setText("View Patent Details");

        btnAddVitalSign.setBackground(new java.awt.Color(51, 51, 51));
        btnAddVitalSign.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddVitalSign.setForeground(new java.awt.Color(255, 255, 255));
        btnAddVitalSign.setText("Add Visit");
        btnAddVitalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalSignActionPerformed(evt);
            }
        });

        btnViewVitalSigns.setBackground(new java.awt.Color(51, 51, 51));
        btnViewVitalSigns.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewVitalSigns.setForeground(new java.awt.Color(255, 255, 255));
        btnViewVitalSigns.setText("View Past Visits");
        btnViewVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVitalSignsActionPerformed(evt);
            }
        });

        btnAddPrescription.setBackground(new java.awt.Color(51, 51, 51));
        btnAddPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddPrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPrescription.setText("Add Prescription");
        btnAddPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrescriptionActionPerformed(evt);
            }
        });

        btnViewPrescriptions.setBackground(new java.awt.Color(51, 51, 51));
        btnViewPrescriptions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewPrescriptions.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPrescriptions.setText("View Prescription");
        btnViewPrescriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPrescriptionsActionPerformed(evt);
            }
        });

        btnAddSurgery.setBackground(new java.awt.Color(51, 51, 51));
        btnAddSurgery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddSurgery.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSurgery.setText("Add Surgery");
        btnAddSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSurgeryActionPerformed(evt);
            }
        });

        btnViewSurgeries.setBackground(new java.awt.Color(51, 51, 51));
        btnViewSurgeries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewSurgeries.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSurgeries.setText("View Surgeries");
        btnViewSurgeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSurgeriesActionPerformed(evt);
            }
        });

        btnMonitorPatient.setBackground(new java.awt.Color(51, 51, 51));
        btnMonitorPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMonitorPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnMonitorPatient.setText("Monitor Patient");
        btnMonitorPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorPatientActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Patient ID:");

        lblPatientID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Patient Name:");

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Gender:");

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Age:");

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        tblPatientHistory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tblPatientHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Visit Date", "Last Visit Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatientHistory.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPatientHistory);
        if (tblPatientHistory.getColumnModel().getColumnCount() > 0) {
            tblPatientHistory.getColumnModel().getColumn(0).setResizable(false);
            tblPatientHistory.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblPatientHistory.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Recent Visits");

        btnAskForLabProcedures.setBackground(new java.awt.Color(51, 51, 51));
        btnAskForLabProcedures.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAskForLabProcedures.setForeground(new java.awt.Color(255, 255, 255));
        btnAskForLabProcedures.setText("Raise Lab Req");
        btnAskForLabProcedures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAskForLabProceduresActionPerformed(evt);
            }
        });

        btnEmergencyAddition.setBackground(new java.awt.Color(51, 51, 51));
        btnEmergencyAddition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEmergencyAddition.setForeground(new java.awt.Color(255, 255, 255));
        btnEmergencyAddition.setText("Emergency Addition");
        btnEmergencyAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergencyAdditionActionPerformed(evt);
            }
        });

        btnViewProcedures.setBackground(new java.awt.Color(51, 51, 51));
        btnViewProcedures.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewProcedures.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProcedures.setText("View Procedures");
        btnViewProcedures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProceduresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAddVitalSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewVitalSigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddPrescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewPrescriptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddSurgery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewSurgeries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMonitorPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAskForLabProcedures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEmergencyAddition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewProcedures, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddVitalSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddSurgery, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewVitalSigns, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewPrescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewSurgeries, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewProcedures, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAskForLabProcedures, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMonitorPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnEmergencyAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddVitalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalSignActionPerformed
        // TODO add your handling code here:
        AddVitalSignsJPanel addVitalSignsJPanel = new AddVitalSignsJPanel(cardContainer, account, patient, hospital);
        cardContainer.add("addVitalSignsJPanel",addVitalSignsJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnAddVitalSignActionPerformed

    private void btnViewVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVitalSignsActionPerformed
        // TODO add your handling code here:
        ViewPastMedicalRecordJPanel viewPastMedicalRecordJPanel = new ViewPastMedicalRecordJPanel(cardContainer, account, patient, hospital, "VitalSign");
        cardContainer.add("viewPastMedicalRecordJPanel",viewPastMedicalRecordJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnViewVitalSignsActionPerformed

    private void btnAddPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrescriptionActionPerformed
        // TODO add your handling code here:
        AddPrescriptionJPanel addPrescriptionJPanel = new AddPrescriptionJPanel(cardContainer, account, patient, hospital);
        cardContainer.add("addPrescriptionJPanel", addPrescriptionJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnAddPrescriptionActionPerformed

    private void btnViewPrescriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPrescriptionsActionPerformed
        // TODO add your handling code here:
        ViewPastMedicalRecordJPanel viewPastMedicalRecordJPanel = new ViewPastMedicalRecordJPanel(cardContainer, account, patient, hospital, "Prescription");
        cardContainer.add("viewPastMedicalRecordJPanel",viewPastMedicalRecordJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnViewPrescriptionsActionPerformed

    private void btnAddSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSurgeryActionPerformed
        // TODO add your handling code here:
        AddSurgeryJPanel addSurgeryJPanel = new AddSurgeryJPanel(cardContainer, account, patient, hospital);
        cardContainer.add("addSurgeryJPanel", addSurgeryJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnAddSurgeryActionPerformed

    private void btnViewSurgeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSurgeriesActionPerformed
        // TODO add your handling code here:
        ViewPastMedicalRecordJPanel viewPastMedicalRecordJPanel = new ViewPastMedicalRecordJPanel(cardContainer, account, patient, hospital, "Surgery");
        cardContainer.add("viewPastMedicalRecordJPanel",viewPastMedicalRecordJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnViewSurgeriesActionPerformed

    private void btnMonitorPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorPatientActionPerformed
        // TODO add your handling code here:
        MonitorPatientForTestsJPanel monitorPatientForTestsJPanel = new MonitorPatientForTestsJPanel(cardContainer, account, patient);
        cardContainer.add("monitorPatientForTestsJPanel", monitorPatientForTestsJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnMonitorPatientActionPerformed

    private void btnAskForLabProceduresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAskForLabProceduresActionPerformed
        // TODO add your handling code here:
        RaiseLabRequestJPanel raiseLabRequestJPanel = new RaiseLabRequestJPanel(cardContainer, account, hospital, patient);
        cardContainer.add("raiseLabRequestJPanel", raiseLabRequestJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnAskForLabProceduresActionPerformed

    private void btnEmergencyAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyAdditionActionPerformed
        // TODO add your handling code here:
        EmergencyMedicalDataAdditionJPanel emergencyMedicalDataAdditionJPanel = new EmergencyMedicalDataAdditionJPanel(cardContainer, account, patient, hospital);
        cardContainer.add("emergencyMedicalDataAdditionJPanel", emergencyMedicalDataAdditionJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnEmergencyAdditionActionPerformed

    private void btnViewProceduresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProceduresActionPerformed
        // TODO add your handling code here:
        ViewPastMedicalRecordJPanel viewPastMedicalRecordJPanel = new ViewPastMedicalRecordJPanel(cardContainer, account, patient, hospital, "Procedures");
        cardContainer.add("viewPastMedicalRecordJPanel",viewPastMedicalRecordJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnViewProceduresActionPerformed

    private void goBack(){
        cardContainer.remove(this);
        Component[] componentArray = cardContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if(type.equals("Emergency")){
            EmergencyAssignmentsJPanel emergencyAssignmentsJPanel = (EmergencyAssignmentsJPanel) component;
            emergencyAssignmentsJPanel.populatePatientsTable();
        }else if(type.equals("General")){
            ViewPatientsJPanel viewPatientsJPanel = (ViewPatientsJPanel) component;
            viewPatientsJPanel.populatePatientsTable();
        }
        CardLayout layout = (CardLayout)cardContainer.getLayout();
        layout.previous(cardContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrescription;
    private javax.swing.JButton btnAddSurgery;
    private javax.swing.JButton btnAddVitalSign;
    private javax.swing.JButton btnAskForLabProcedures;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEmergencyAddition;
    private javax.swing.JButton btnMonitorPatient;
    private javax.swing.JButton btnViewPrescriptions;
    private javax.swing.JButton btnViewProcedures;
    private javax.swing.JButton btnViewSurgeries;
    private javax.swing.JButton btnViewVitalSigns;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTable tblPatientHistory;
    // End of variables declaration//GEN-END:variables
}
