/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.hospitalAdmin;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import source.department.Department;
import source.department.Department.DepartmentType;
import source.hospital.Hospital;
import source.userAccount.UserAccount;
import source.util.UtilFunctions;

/**
 *
 * @author GaurangDeshpande
 */
public class ManageHospitalsJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private UserAccount account;
    private Hospital selectedHospitalBranch;
    private Department department;
    private DepartmentType selectedDepartment;
    private static Logger log;
    
    /**
     * Creates new form ManageHospitalsJPanel
     */
    ManageHospitalsJPanel(JPanel cardContainer, UserAccount account, Hospital selectedHospitalBranch) {
        initComponents();
        this.cardContainer = cardContainer;
        this.account = account;
        this.selectedHospitalBranch = selectedHospitalBranch;
        log = Logger.getLogger(ManageHospitalsJPanel.class);
        
        lblLoggedInUser.setText(account.getEmployee().getPerson().getLastName()+", "+account.getEmployee().getPerson().getFirstName());
        lblHeading.setText("Manage Hospitals - "+selectedHospitalBranch);
        lblHospitalBranch.setText(""+selectedHospitalBranch);
        populateDepartments();
        populateTableAccordingToSelectedHospital();
    }
    
    private void populateDepartments() {
        cmbDepartments.removeAllItems();
        cmbDepartments.addItem("Select a department");
        if (selectedHospitalBranch!=null&&(!selectedHospitalBranch.getDepartmentDirectory().getDepartmentList().isEmpty())) {
            ArrayList<DepartmentType> departmentList = new ArrayList<>();
            for (DepartmentType dep : Department.DepartmentType.values()) {
                int i=0;
                for (Department depart : selectedHospitalBranch.getDepartmentDirectory().getDepartmentList()) {
                    if (dep.getValue().equals(depart.getName())) {
                        i++;
                        break;
                    }
                }
                if(i==0){
                    cmbDepartments.addItem(dep);
                }
            }
        } else {
            for (Department.DepartmentType department : Department.DepartmentType.values()) {
                cmbDepartments.addItem(department);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblLoggedInUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDepartments = new javax.swing.JComboBox();
        btnAddDepartment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitalDepartments = new javax.swing.JTable();
        btnDeleteDepartment = new javax.swing.JButton();
        lblHospitalBranch = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblHeading.setText("Manage Hospitals");

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Hospital Branch:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Add Department:");

        cmbDepartments.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cmbDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentsActionPerformed(evt);
            }
        });

        btnAddDepartment.setBackground(new java.awt.Color(51, 51, 51));
        btnAddDepartment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDepartment.setText("Add Department");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        tblHospitalDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department", "Dept ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospitalDepartments);
        if (tblHospitalDepartments.getColumnModel().getColumnCount() > 0) {
            tblHospitalDepartments.getColumnModel().getColumn(0).setResizable(false);
            tblHospitalDepartments.getColumnModel().getColumn(1).setResizable(false);
        }

        btnDeleteDepartment.setBackground(new java.awt.Color(51, 51, 51));
        btnDeleteDepartment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteDepartment.setText("Delete Department");
        btnDeleteDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDepartmentActionPerformed(evt);
            }
        });

        lblHospitalBranch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDepartments, 0, 262, Short.MAX_VALUE)
                                    .addComponent(lblHospitalBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDeleteDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(324, 324, 324))
                                    .addComponent(jScrollPane1)))
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblHospitalBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void goBack(){
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }
    
    private void populateTableAccordingToSelectedHospital() {
        DefaultTableModel dtm = (DefaultTableModel) tblHospitalDepartments.getModel();
        dtm.setRowCount(0);
        if (selectedHospitalBranch != null) {
            for (Department depart : selectedHospitalBranch.getDepartmentDirectory().getDepartmentList()) {
                for (DepartmentType dep : Department.DepartmentType.values()) {
                    if (dep.getValue().equals(depart.getName())) {
                        Object[] row = new Object[2];
                        row[0] = depart;
                        row[1] = depart.getDepartmentID();
                        dtm.addRow(row);
                    }
                }
            }
        }
    }
    
    private void cmbDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentsActionPerformed
        // TODO add your handling code here:
        if (cmbDepartments.getItemCount() != 0) {
            if (cmbDepartments.getSelectedItem().equals("Select a department")) {
                btnAddDepartment.setVisible(false);
                selectedDepartment = null;
            } else {
                btnAddDepartment.setVisible(true);
                selectedDepartment = (DepartmentType) cmbDepartments.getSelectedItem();
            }
        }
    }//GEN-LAST:event_cmbDepartmentsActionPerformed

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // TODO add your handling code here:
        if(selectedDepartment!=null && selectedHospitalBranch!=null){
            department=selectedHospitalBranch.getDepartmentDirectory().createDepartment(selectedDepartment);
            System.out.println(selectedHospitalBranch.getHospitalBranchName());
            log.info(UtilFunctions.encrypt("ADD_DEP : "+account.getEmployee()));
            System.out.println(department.getDepartmentID()+" "+department.getName());
            System.out.println("Total departments --> "+selectedHospitalBranch.getDepartmentDirectory().getDepartmentList().size());
            populateTableAccordingToSelectedHospital();
            populateDepartments();
        }
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnDeleteDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDepartmentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHospitalDepartments.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a department to delete", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Department dept = (Department) tblHospitalDepartments.getValueAt(selectedRow, 0);
            log.info(UtilFunctions.encrypt("DEL_DEP : "+account.getEmployee()));
            selectedHospitalBranch.getDepartmentDirectory().deleteDepartment(dept);
            populateTableAccordingToSelectedHospital();
            populateDepartments();
        }
    }//GEN-LAST:event_btnDeleteDepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteDepartment;
    private javax.swing.JComboBox cmbDepartments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHospitalBranch;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JTable tblHospitalDepartments;
    // End of variables declaration//GEN-END:variables
}
