/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.patient;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import org.apache.log4j.Logger;
import source.patient.Patient;
import source.patient.TestFindings;
import source.userAccount.UserAccount;
import source.util.UtilFunctions;

/**
 *
 * @author GaurangDeshpande
 */
public class TakeTestJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private UserAccount account;
    private static int countdown = 0;
    private Timer timer;
    private Patient patient;
    private DecimalFormat format;
    private static int tappesInTest = 0;
    private String testType;
    private static Logger log;
    
    //private static 
    /**
     * Creates new form TakeTestJPanel
     */
    TakeTestJPanel(JPanel cardContainer, UserAccount account) {
        initComponents();
        this.cardContainer = cardContainer;
        this.account = account;
        this.patient=account.getPatient();
        lblLoggedInUser.setText(account.getPatient().getPerson().getLastName()+", "+account.getPatient().getPerson().getFirstName());
        log = Logger.getLogger(TakeTestJPanel.class);
        preparation();
        //initialSetup();
    }
    
    private void preparation(){
        btnBefore.setEnabled(true);
        btnAfter.setEnabled(true);
        
        countdown = 0;
        btnStartTest.setEnabled(false);
        btnTapA.setEnabled(false);
        btnTapB.setEnabled(false);
        
        format = new DecimalFormat("00");
        lblTimer.setText("00:"+format.format(countdown));
    }
    
    private void initialSetup(){
        format = new DecimalFormat("00");
        lblTimer.setText("00:"+format.format(countdown));
        
        tappesInTest = 0;
        
        btnTapA.setEnabled(false);
        btnTapB.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblLoggedInUser = new javax.swing.JLabel();
        btnStartTest = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();
        btnTapA = new javax.swing.JButton();
        btnTapB = new javax.swing.JButton();
        btnBefore = new javax.swing.JButton();
        btnAfter = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblHeading.setText("Patient Details");

        lblLoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoggedInUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        btnStartTest.setBackground(new java.awt.Color(51, 51, 51));
        btnStartTest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStartTest.setForeground(new java.awt.Color(255, 255, 255));
        btnStartTest.setText("Begin Test");
        btnStartTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTestActionPerformed(evt);
            }
        });

        lblTimer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("jLabel1");

        btnTapA.setBackground(new java.awt.Color(51, 51, 51));
        btnTapA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTapA.setForeground(new java.awt.Color(255, 255, 255));
        btnTapA.setText("Tap Here!");
        btnTapA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTapAActionPerformed(evt);
            }
        });

        btnTapB.setBackground(new java.awt.Color(51, 51, 51));
        btnTapB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTapB.setForeground(new java.awt.Color(255, 255, 255));
        btnTapB.setText("Tap Here!");
        btnTapB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTapBActionPerformed(evt);
            }
        });

        btnBefore.setBackground(new java.awt.Color(51, 51, 51));
        btnBefore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBefore.setForeground(new java.awt.Color(255, 255, 255));
        btnBefore.setText("Before");
        btnBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeforeActionPerformed(evt);
            }
        });

        btnAfter.setBackground(new java.awt.Color(51, 51, 51));
        btnAfter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAfter.setForeground(new java.awt.Color(255, 255, 255));
        btnAfter.setText("After");
        btnAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnTapA, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTapB, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnStartTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 366, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnStartTest, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTapA, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnTapB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnStartTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTestActionPerformed
        // TODO add your handling code here:
        btnTapA.setEnabled(true);
        btnTapB.setEnabled(false);
        log.info(UtilFunctions.encrypt("TAP_TEST : "+account.getPatient().getPerson().getFirstName()+" "+account.getPatient().getPerson().getLastName()));
        if(countdown!=0){
            countdown=0;
            lblTimer.setText("00:"+String.valueOf(format.format(countdown)));
        }
        
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                countdown++;
                lblTimer.setText("00:"+String.valueOf(format.format(countdown)));
                if(countdown>=10){
                    timer.stop();
                    System.out.println("---------Test Stopped--------");
                    btnTapA.setEnabled(false);
                    btnTapB.setEnabled(false);
                    btnStartTest.setEnabled(false);
                    btnBefore.setEnabled(true);
                    btnAfter.setEnabled(true);
                    
                    System.out.println("Number of taps in test--->"+tappesInTest);
                    if (testType.equalsIgnoreCase("Before")) {
                        TestFindings finding = patient.getTestFindingHistory().addTestFindings();
                        finding.setTappingCountBefore(tappesInTest);
                        finding.setTimeStamp(new Date());
                    } else if (testType.equalsIgnoreCase("After")) {
                        TestFindings finding = patient.getTestFindingHistory().addTestFindings();
                        finding.setTappingConntAfter(tappesInTest);
                        finding.setTimeStamp(new Date());
                    }
                    tappesInTest=0;
                }
            }
        };
        
        timer = new Timer(1000, listener);
        timer.start();
        System.out.println("---------Test Started---------");
    }//GEN-LAST:event_btnStartTestActionPerformed

    private void btnTapAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTapAActionPerformed
        // TODO add your handling code here:
        tappesInTest++;
        btnTapA.setEnabled(false);
        btnTapB.setEnabled(true);
    }//GEN-LAST:event_btnTapAActionPerformed

    private void btnTapBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTapBActionPerformed
        // TODO add your handling code here:
        tappesInTest++;
        btnTapA.setEnabled(true);
        btnTapB.setEnabled(false);
    }//GEN-LAST:event_btnTapBActionPerformed

    private void btnBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeforeActionPerformed
        // TODO add your handling code here:
        btnAfter.setEnabled(false);
        btnStartTest.setEnabled(true);
        btnTapA.setEnabled(false);
        btnTapB.setEnabled(false);
        
        format = new DecimalFormat("00");
        lblTimer.setText("00:"+format.format(countdown));
        
        testType="Before";
        
        if(countdown!=0){
            countdown=0;
            lblTimer.setText("00:"+String.valueOf(format.format(countdown)));
        }
    }//GEN-LAST:event_btnBeforeActionPerformed

    private void btnAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfterActionPerformed
        // TODO add your handling code here:
        btnBefore.setEnabled(false);
        btnStartTest.setEnabled(true);
        btnTapA.setEnabled(false);
        btnTapB.setEnabled(false);
        
        format = new DecimalFormat("00");
        lblTimer.setText("00:"+format.format(countdown));
        
        testType="After";
        
        if(countdown!=0){
            countdown=0;
            lblTimer.setText("00:"+String.valueOf(format.format(countdown)));
        }
    }//GEN-LAST:event_btnAfterActionPerformed

    private void goBack(){
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfter;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBefore;
    private javax.swing.JButton btnStartTest;
    private javax.swing.JButton btnTapA;
    private javax.swing.JButton btnTapB;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLoggedInUser;
    private javax.swing.JLabel lblTimer;
    // End of variables declaration//GEN-END:variables
}
